import { useState } from "react";
import { Sparkles, Copy, Loader2 } from "lucide-react";
import toast from 'react-hot-toast';
import api from "../utils/api";
import { useContext } from "react";
import { UserContext } from "../components/userContext";

const Generate = () => {
  const [inputText, setInputText] = useState("");
  const [result, setResult] = useState("");
  const [loading, setLoading] = useState(false);

  const { fetchUser } = useContext(UserContext);

  const handleGenerate = async (e) => {
    e.preventDefault();

    try {
      setLoading(true);

      const response = await api.post("/api/generation/create",{
        inputText
      });

      setResult(response.data.generation);
      fetchUser();
      setInputText("");
      toast.success(response.data.message);

    } catch (error) {
      console.log(error);
      toast.error(error.response?.data?.message || "Generation failed");  
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="space-y-12">

      {/* ================= INPUT SECTION ================= */}
      <div className="bg-white/5 border border-white/10 rounded-3xl p-10 backdrop-blur-xl">

        <h2 className="text-2xl font-semibold mb-6">
          Describe Your Startup Idea
        </h2>

        <textarea
          rows="6"
          value={inputText}
          onChange={(e) => setInputText(e.target.value)}
          placeholder="Example: I want to build an AI tool that matches students with internships automatically..."
          className="w-full bg-[#0E1424] border border-white/10 rounded-2xl p-6 text-gray-300 focus:outline-none focus:border-purple-500 transition resize-none"
        />

        <div className="grid md:grid-cols-3 gap-6 mt-8">
          <input
            placeholder="Target Users (Optional)"
            className="bg-[#0E1424] border border-white/10 rounded-xl p-4 focus:outline-none focus:border-purple-500 transition"
          />
          <select className="bg-[#0E1424] border border-white/10 rounded-xl p-4">
            <option>Budget: Bootstrapped</option>
            <option>Budget: $5k - $20k</option>
            <option>Budget: Funded Startup</option>
          </select>
          <select className="bg-[#0E1424] border border-white/10 rounded-xl p-4">
            <option>Timeline: 1 Month</option>
            <option>Timeline: 3 Months</option>
            <option>Timeline: 6+ Months</option>
          </select>
        </div>

        
        <button
          onClick={handleGenerate}
          disabled={loading}
          className={`mt-10 px-10 py-4 rounded-xl font-semibold flex items-center gap-3 transition shadow-lg
          ${
            loading
              ? "bg-gray-700 cursor-not-allowed opacity-70"
              : "bg-gradient-to-r from-purple-600 to-cyan-500 hover:scale-105 shadow-purple-600/30 cursor-pointer hover:shadow-[0_0_25px_rgba(124,58,237,0.6)]"
          }`}
        >
          {loading ? (
            <>
              <Loader2 className="animate-spin h-5 w-5" />
              Generating...
            </>
          ) : (
            <>
              <Sparkles size={18} />
              Generate Blueprint
            </>
          )}
        </button>

      </div>

      {/* ================= OUTPUT SECTION ================= */}
      {result && (
        <div className="min-h-screen bg-[#0B0F19] text-white px-6 md:px-20 py-16">

  {/* Page Header */}
  <div className="mb-16">
    <h1 className="text-4xl md:text-5xl font-bold">
      <span className="bg-gradient-to-r from-[#00F5FF] via-[#7C3AED] to-[#FF00E5] bg-clip-text text-transparent">
        Generated AI Blueprint
      </span>
    </h1>
    <p className="text-gray-400 mt-4">
      Structured architecture overview generated by AI.
    </p>
  </div>

  {/* Blueprint Content */}
  <div className="space-y-14">

      {Object.entries(
          typeof result.aiResponse === "string"
            ? JSON.parse(result.aiResponse)
            : result.aiResponse
        ).map(([sectionKey, section]) => (

          <div key={sectionKey} className="border-b border-white/10 pb-10">

            {/* Section Title */}
            <h2 className="text-2xl font-semibold mb-4 capitalize text-[#7C3AED]">
              {sectionKey.replace(/([A-Z])/g, " $1")}
            </h2>

            {/* Summary */}
            <p className="text-gray-400 mb-6 leading-relaxed">
              {section.summary}
            </p>

            {/* Bullet Points */}
            <ul className="space-y-3 text-gray-300">
              {section.bullets.map((bullet, index) => (
                <li
                  key={index}
                  className="pl-5 border-l-2 border-[#00F5FF]/50"
                >
                  {bullet}
                </li>
              ))}
            </ul>

          </div>

        ))}

      </div>
    </div>


      )}
    </div>
  );
};

export default Generate;


/* ================= Reusable Info Card ================= */

